---
# tasks file for firewall

- name: Check if firewall is installed and install it.
  yum:
    name: firewalld
    state: present

- name: Add ports to firewall
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop: "{{ firewall_ports_to_open }}"
  notify:
    - Reload firewalld

- name: Enable firewalld
  service:
    name: firewalld
    enabled: yes